version: "3"

services:
  recebeCep:
    container_name: recebeCep
    build:
      context: ./recebeCep
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
    networks:
      - local-network

  temperaturaCep:
    container_name: temperaturaCep
    build:
      context: ./temperaturaCep
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
    networks:
      - local-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge